- no-littering.el
Not sure if you want the order to be project `ensime` or var `user-emacs-ensime-directory`
> Add ensime

- no-littering.el
Added a configuration for company-statistics-file.
> company-statistics: theme company-statistics-file

- no-littering.el
Theme `yas-snippet-dirs' and create required directory.
> yasnippet: theme yas-snippet-dirs

- README.md
The first suggestion shows how to ignore no-littering files in recentf.
> Add Suggested Settings section to README

- no-littering.el
GitHub won't let me reopen PR #49 because I force-pushed to the master branch of my fork.
> indium: theme indium-workspace-file

- no-littering.el
> Please try to follow the [conventions](https://github.com/tarsius/no-littering#conventions).
> 
> Also please link to the repository of the package that your pull request is theming.
https://www.emacswiki.org/emacs/irfc.el
> irfc: theme irfc-directory

- no-littering.el
I think I followed all conventions. Please tell me if I didn't. The only thing I'm not sure about is if the subdirectory "cache/" is necessary or if "omnisharp/" would have been enough. There is no other variable to theme.
> please link to the repository of the package that your pull request is theming.
- https://github.com/OmniSharp/omnisharp-emacs
> omnisharp: theme omnisharp-cache-directory

- no-littering.el
Location where all the folders for the backup git repositories are.
> helm-backup: theme helm-backup-path

- no-littering.el
amx-save-file is a cache of amx-data and amx-history
https://github.com/DarwinAwardWinner/amx
> amx: theme amx-save-file

- README.md
See https://www.gnu.org/software/emacs/manual/html_node/emacs/Saving-Customizations.html.
> Add note about custom-file to README.md

- no-littering.el
See:
https://www.gnu.org/software/emacs/manual/html_node/emacs/Format-of-Diary-File.html
> diary: theme diary-file

- no-littering.el
This folder is used to hold the binaries of tabnine, the all language completer.
See https://github.com/TommyX12/company-tabnine/blob/master/company-tabnine.el#L202
> Theme `company-tabnine-binaries-folder`.

- no-littering.el
Theme Wanderlust and its subpackage elmo's variables.
https://github.com/wanderlust/wanderlust/blob/master/wl/wl-vars.el
- `wl-init-file`
- `wl-folders-file`
- `wl-address-file`
- `wl-alias-file`
https://github.com/wanderlust/wanderlust/blob/master/elmo/elmo-vars.el
- `elmo-msgdb-directory`
https://github.com/wanderlust/wanderlust/blob/master/elmo/elmo-split.el
- `elmo-split-log-file`
> Theme Wanderlust and its subpackage elmo's variables.

- no-littering.el
> org-recent-headings: Theme org-recent-headings-save-file

- no-littering.el
Hello!
This adds support for annotate.el 
https://github.com/bastibe/annotate.el
This is the only data file of the package and stores s-expressions.
Thank you!
C.
> annotate.el: theme annotate-file

- no-littering.el
This PR adds support for [psession](https://github.com/thierryvolpiatto/psession).
If anything needs to be changed, feel free to ask and I'll update the PR accordingly.
> psession: theme psession-elisp-objects-default-directory

- no-littering.el
- This file stores an s-expression encrypted with gnupg (using epa).
- This is the only configuration/data file of the package.
- This package does take care of creating the containing directory if
necessary.
Repository for libbcel: https://gitea.petton.fr/bcel/libbcel
> libbcel: theme libbcel-oauth-store-filename

- no-littering.el
- This is a directory, and the package takes care of creating it.
- undohist is a third party package available from MELPA ([git repo](https://github.com/emacsorphanage/undohist))
> undohist: theme undohist-directory

- no-littering.el
> auto-package-update: theme auto-package-last-update-day-path

- no-littering.el
[link] : [command-log-mode](https://github.com/lewang/command-log-mode)
- Third-Party package
- This is the only data directory of the package to save log files.
- This package doesn't take care of creating the containing
directory if necessary. 
- variable name is abbreviation of package's name
> command-log-mode: theme clm/logging-dir

- no-littering.el
- The package creates the directory if it doesn't exist
- Package repo: https://github.com/ydistri/nomad-tramp
- I'm the maintainer
> nomad-tramp: theme nomad-tramp-script-directory

- README.org
- no-littering.el
Please see the wip problem description at https://github.com/emacscollective/no-littering/blob/safer-backups/README.org#backup-files.
> Document and optionally reduce risk of leaking secrets
