emacscollective/no-littering

- no-littering.el
auto-save files get created for each new PID and this creates quite a bit of
clutter in var.
What do you think @tarsius? I did this because my var directory was filling up with these files.
> auto-save: Move files into a directory

- README.md
- no-littering.el
Correction applied to both the Emacs Lisp and Markdown files. Removed some
trivial errors highlighted by Flycheck as well.
> Correct a typographical error in the package conventions

- no-littering.el
Add Vimish Folds persistent cache dir.  VF creates dir automatically.
Consequently fix errant whitespace.
https://github.com/mrkkrp/vimish-fold
> vimish-fold:theme vimish-fold directory

- no-littering.el
Both `desktop-path` and `desktop-dirname` should be set to the directory created by `no-littering`. Currently only `desktop-path` is set which means that `desktop-mode` asks for path when closing emacs.
> Add desktop-dirname

- no-littering.el
https://gitlab.petton.fr/nico/elbank
- This file is used to store a JSON document.
- This is the only data file of the package.
- This package does take care of creating the containing directory if
necessary.
> elbank: theme elbank-data-file

- no-littering.el
elbank switched from json to emacs lisp file format (in [#4a0905d4](https://gitlab.petton.fr/nico/elbank/commit/4a0905d4cb28f746ad6e012acf9f0d28d525ff09)).
> elbank: re-theme elbank-data-file

- no-littering.el
See https://github.com/ahungry/geben.
This is the only configurable path of the package.
> geben: theme geben-temporary-file-directory

- no-littering.el
meghanada is a Java completion engine.
This is the directory to store the meghanada server which will be conneced when
enable meghanada mode. When call `meghanada-update-server', it will download it
from 'dl.bintray.com'.
See also: https://github.com/mopemope/meghanada-emacs/blob/98ad6a5361c725319a355522d2d1ba0e0fbb7cde/meghanada.el#L107
Happy new year!
> meghanada: theme `meghanada-server-install-dir'

- no-littering.el
there are two file settings, but a subdirectory is not needed, since
in practice there is only one file (the lock file is not persistent).
> add support for keyfreq: keyfreq-file and keyfreq-file-lock

- no-littering.el
- This file is used to save and restore the last reading places.
- This is the only configuration/data file of the package.
> nov: theme nov-save-place-file

- no-littering.el
This variable was made obsolete and using it issues a warning when loading yasnippet now 
https://github.com/joaotavora/yasnippet/commit/b1ca2197062340d4c9e78442ea38957a96f968d4
> yasnippet: remove obsolete yas-installed-snippets-dir

- no-littering.el
Theme `purpose-default-layout-file` and `purpose-layout-dirs`.
purpose-default-layout-file:
purpose-layout-dirs:
- Files stored here are also used for s-expressions, but the package does not allow changing the
file name extensions.
Upstream: https://github.com/bmag/emacs-purpose
> window-purpose: theme variables

- README.md
- no-littering.el
I think repeating the logic makes it a lot clearer.
I get it that we are following the unix/linux conventions but sometimes I have doubts what should go where.  Are bookmarks configuration or data? I think it's both.  Do I want to version bookmarks? Do I want to version `var/` or only `etc/` or neither?  These are some additional questions I have that this PR does not address.  Do we have good answers?
Fix #78
> Clarify the roles of etc/var directories

- no-littering.el
pandoc-mode repository: https://github.com/joostkremers/pandoc-mode
The `pandoc-data-dir` directory really contains config, not data, even though the variable is named `pandoc-data-dir`. The config files contain S-expressions describing the desired options for pandoc output formats.
> pandoc-mode: theme `pandoc-data-dir'

- no-littering.el
Treemacs is a tree layout file explorer for Emacs.
https://github.com/Alexander-Miller/treemacs
- This file is used to store Treemacs workspaces between sessions.
- The workspaces are saved in an org compatible format.
> treemacs: theme treemacs-persist-file

- no-littering.el
This file is used to store an s-expression.  This is the only data file of the package to date, but the package places the file in a subdirectory of its own by default, to accommodate future files.  This package takes care of creating the containing directory if necessary.
Homepage: https://github.com/clarete/hackernews.el
> hackernews: theme hackernews-visited-links-file

- no-littering.el
- This file is used to store an s-expression (albeit, not one that is easy to edit).
- This is the only ~~configuration/~~ data file of the package (although it's a package that sees a lot of action, who knows how long that will last).
- This package ~~does/~~ doesn't take care of creating the containing directory if necessary.
Upstream: https://github.com/emacs-lsp/lsp-mode
Sinful lines: https://github.com/emacs-lsp/lsp-mode/blob/master/lsp.el#L167-L170
> lsp: theme lsp-session-file

- no-littering.el
- This file is used to store breakpoints
- This is the only configuration/data file of the package.
Link to repo: https://github.com/yyoncho/dap-mode
> dap-mode: theme dap-breakpoints

- no-littering.el
logview-cache-filename:
- This file is used to store cache data
logview-views-file:
- This file is used to store different views (/filters)
Repo link: https://github.com/doublep/logview
> logview: theme logview-cache-filename and logview-views-file

- no-littering.el
This directory is used to store an s-expression file generated from
the PDF.  The generated file is named <sha1>_v3 in this directory.
The package will create the directory if it does not exist.
https://github.com/skeeto/x86-lookup
> x86-lookup: theme x86-lookup-cache-directory

- no-littering.el
This adds support for [prescient.el](https://github.com/raxod502/prescient.el) written by @raxod502.
This seems to be the only file variable in the package.
> prescient: Theme prescient-save-file

- no-littering.el
This file is used to store the CIDER REPL history. It stores s-expressions, and the content is similar to the following:
```
;; -*- coding: utf-8-unix -*-
;; Automatically written history of CIDER REPL session
;; Edit at your own risk
("(go)" "(halt)")
```
> CIDER: theme cider-repl-history-file

- no-littering.el
Package here: https://github.com/emacs-lsp/lsp-python-ms
- This is the only data directory of the package.
- It stores downloaded binary data/executables.
- This package does take care of of creating the containing directory if necessary.
> lsp-python-ms: theme lsp-python-ms-dir

- no-littering.el
https://github.com/shlevy/nix-buffer
This is the only custom file/directory variable in the package. It is a directory that contains build results of Nix and possibly a file named "trusted-exprs".
> nix-buffer: Theme nix-buffer-directory-name

- no-littering.el
Package: [ideasman42/emacs-undo-fu-session](https://gitlab.com/ideasman42/emacs-undo-fu-session)
* This is the only configuration/data directory of the package.
* The files are used to store s-expressions.
* This package does take care of creating the directory if necessary.
Please ignore the previous PR, I messed up. I guess that's what I get for trying to use the GitHub web UI for a quick edit instead of using Magit...
> undo-fu-session: theme undo-fu-session-directory

- no-littering.el
The server subdirectory might have the same problem, but my usage does
not involve that one so I only encountered this one error and was too
lazy to test the other one as it seems to require 3rd party
executables.
> Fix omission from 79a7650 (create "lsp" directory)

- no-littering.el
- This is the only configuration file of the package
- This file is loaded with eudc and sets config variables
Example of the file contents:
````elisp
;; This file was automatically generated by eudc.el.
(provide 'eudc-options-file)
(eudc-set-server "ldap://localhost:1389" 'ldap t)
(setq eudc-server-hotlist '(("ldap://localhost:1389" . ldap)))
````
Personally, I don't understand why eudc needs to save all these variables in a custom file and load it, in a way re-implementing the customize-interface. There is a function `eudc-edit-hotlist` that lets you edit the hotlist in a special buffer. But what’s the use? Why not just use a correct custom `:type`?
Maybe I should suggest these changes to eudc eventually.
> eudc: theme eudc-options-file

- no-littering.el
- This file is used to store s-expressions
- This is a built-in feature
> filesets: theme filesets-menu-cache-file

- no-littering.el
- This file is used to store an s-expression. (Merely a list of integers, tho)
- Third-party package. https://www.emacswiki.org/emacs/TypeBreakMode
> type-break: theme type-break-file-name

- no-littering.el
This var was recently added to log curl errors when
helm-net-prefer-curl is set to t.
See: https://github.com/emacs-helm/helm/commit/dee9e48fa76ad4a0d7b4ad1f6f3e7dd53e74d7cd
> helm: theme helm-net-curl-log-file

- no-littering.el
- Third-party package. https://thelambdalab.xyz/elpher/
> elpher: theme elpher-bookmarks-file

- no-littering.el
This is a built-in package. 
- The file is used to store s-expressions.
- This is the only configuration/data file of the package that I know of. It is the only one listed in the Customization buffer.
- The file is by default stored at the top level of the user Emacs directory.
Thank you.
> calc: theme calc-settings-file

- no-littering.el
Equake[1]  needs to be able to figure out what display to open on. When the
display value is not set in the environment, this task is complicated.  So
as one possible fallback, every time a graphical frame is opened we store
its display value in `equake-persistent-display-file` as a potential cue to
a likely display when the current display value is
unset/inaccessible (i.e. fallback to last known good value).
- This file is used to store raw text.
- This is currently the only configuration/data file of the package.
[1] https://gitlab.com/emacsomancer/equake
> equake: theme equake-persistent-display-file

- no-littering.el
- [persist.el](https://elpa.gnu.org/packages/persist.html) is a third party package providing variables which persist across sessions.
- persist--directory-location is the location of persist directory where the variables are stored.
> persist: theme persist--directory-location

- no-littering.el
abbrev.el stores abbrev tables defined by the user using
s-expressions. Users would typically be inclined to check them into
version control as they would with snippets.
https://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/abbrev.el#n43
Related to #135.
> abbrev: re-theme /var/abbrev.el to /etc/abbrev.el

- no-littering.el
The aliases file stores user-defined aliases used in Eshell. Users
would typically be inclined to check them into version control as they
would with snippets.
The em-alias.el file normally resides inside of the directory
corresponding to eshell-directory-name, and does not assist in
generating an additional containing directory, so we must make that
directory ourselves.
https://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/eshell/em-alias.el#n103
Related to #135.
> eshell: theme eshell-aliases file separately from other eshell files

- no-littering.el
- Built-in package (ecomplete).
> ecomplete: theme ecomplete-database-file

- no-littering.el
- This file is used to store s-expressions that recreate bookmark lists
- This package already has two themed variables
Repo: [https://www.emacswiki.org/emacs/bookmark%2b-bmu.el](https://www.emacswiki.org/emacs/bookmark%2b-bmu.el)
Please let me know if there's anything I didn't do appropriately.
> bmkp: theme bmkp-bmenu-commands-file

- no-littering.el
This file is used to store an s-expression.  This is the only
configuration/data file of the package.
Original package: https://github.com/sp1ff/elfeed-score/
> elfeed-score: theme `elfeed-score-score-file'

- no-littering.el
This file is used to store an s-expression.  This is the only
data file of the package.
Package homepage: https://github.com/007kevin/pdf-view-restore/
> pdf-view-restore: theme `pdf-view-restore-filename'

- no-littering.el
- This file is used to store an s-expression
- Built-in package (package)
> package: theme package-quickstart-file

- README.md
- no-littering.el
When first reading the README, I thought extra configuration would be needed on Linux because of conflicting defaults — the default user directory here is `~/.config/emacs`, so `no-littering`'s defaults of `~/.emacs.d/var/` and `~/.emacs.d/etc/` would need adjustment. After looking at the code, however, I realized that `no-littering` already places `var` and `etc` under `user-default-directory`, whatever that is. This change aligns documentation with what code is already doing (at the cost of slightly heavier prose).
No commit prefix as not related to a package.
> clarify that container defaults to `user-default-directory`

- no-littering.el
URL of the repository: https://github.com/org-roam/org-roam
- This file is used to store an SQLITE3 database.
- This is the only configuration/data file of the package (as far as I know).
- This package takes care of creating the containing directory if necessary (in `org-roam-db`).
> org-roam: theme org-roam-db-location

- README.md
Unquoted, `~` renders as strikeout, so the readme looks like this:
> (defaulting to "etc/" under `user-emacs-directory`, thus usually
> "~/.emacs.d/etc/") and persistent data files in
> `no-littering-var-directory` (defaulting to "var/" under
> `user-emacs-directory`, thus usually "~/.emacs.d/var/"), and
(I've read the conventions file, but I wasn't sure what template to follow given that this is not about a specific package)
> Fix rendering of ~ in README.md

- no-littering.el
URL of the repository: https://github.com/emacs-lsp/lsp-mode
- This file is used to store an s-expression
- There is another configuration option in this package to store a file: `lsp-eslint-unzipped-path`. Nevertheless, I didn't create an `"lsp/eslint/"` directory to store both because this variable has a default value of `(f-join lsp-server-install-dir "eslint/unzipped")`and `lsp-server-install-dir` is already configured by no-littering.
- This package takes care of creating the containing directory thanks to my PR: https://github.com/emacs-lsp/lsp-mode/pull/2559.
> lsp-eslint: theme lsp-eslint-library-choices-file

- no-littering.el
This is response to #158.  @leungbk, do you agree this makes more sense?
This package features four location variables.
The value of `url-configuration-directory` affects the values of the
other three variables.  For some reason only `url-cache-directory` is
set when it is being defined. `url-cookie-file` and `url-history-file`
are initialized to nil and set to proper values when the `url` package
is first used.  This is done in `url-do-setup`.
We have to theme `url-configuration-directory` because third-party
package may put other files in there.  We do however give up on
following the conventions that led us to use "url/configuration/"
as its value.
Instead we use just "url/", which means that the cache directory and
the two files can be placed inside that directory, while also using …
> url: Re-interpret the conventions

- no-littering.el
multisession is a builtin package since Emacs 29.1
The directory is used to store multisession variables. e.g., recently used emojis
> multisession: theme multisession-directory

- no-littering.el
Theme rime-user-data-dir.
emacs-rime is a package for CJK(chinese, japanese, korean) users to input their characters, and `rime-user-data-dir` stores the config files.
https://github.com/DogLooksGood/emacs-rime
https://github.com/DogLooksGood/emacs-rime/blob/5c2ade217134f6f20cd405447af20825e5b44513/rime.el#L356
> rime: theme rime-user-data-dir

- no-littering.el
Please use a dedicated feature branch.  This is why:
https://github.com/magit/magit/wiki/Dedicated-pull-request-branches
Please try to follow the conventions.
https://github.com/tarsius/no-littering#conventions
In the past the majority of contributors have ignored at least some of the conventions.  Others did not fully understand them or had a good reason to depart from the conventions but did not explain why that is so. Unfortunately it is hard for me as the maintainer to tell whether a contributor did not invest enough time to get things right or just forgot to be explicit about their thought process. The result is that a pull request is actually more work for me than a simple "please theme PACKAGE from URL".
Going forward contributors are expected to follow the conventions more closely …
> add lsp-clojure workspace

- no-littering.el
Theme svg-lib-icons-dir from svg-lib package.
Variable definition (https://github.com/rougier/svg-lib/blob/master/svg-lib.el#L133) :
```elisp
(defcustom svg-lib-icons-dir
(expand-file-name (concat user-emacs-directory ".cache/svg-lib/"))
"svg-lib icons directory."
:group 'svg-lib
:type 'directory)
```
> svg-lib: theme svg-lib-icons-dir

- no-littering.el
Fontaine sets font configurations using presets. This elisp-data file
contains a key to the alist `fontaine-presets`, to persist the current
font preset choice across sessions.
By default, it is set to `(locate-user-emacs-file
"fontaine-latest-state.eld")`, we are just moving the same filename to
`var`. It's the only file setting in the package.
Home page with manual: https://protesilaos.com/emacs/fontaine
Source repo: https://git.sr.ht/~protesilaos/fontaine
Please use a dedicated feature branch.  This is why:
https://github.com/magit/magit/wiki/Dedicated-pull-request-branches
Please try to follow the conventions.
https://github.com/tarsius/no-littering#conventions
In the past the majority of contributors have ignored at least some of the conventions.  Others did not fully understand them …
> fontaine: theme fontaine-latest-state-file

- no-littering.el
https://github.com/greghendershott/racket-mode/blob/ab8f953728a653bc6c53681c845a3a69133fdd4d/racket-repl.el#L1228-L1231
The package creates the directory if it doesn't exist.
This is the only configured directory in the package.
> racket-mode: Theme racket-repl-history-directory

- no-littering.el
The `rmh-elfeed-org-files` are the list of configuration files where [elfeed-org](https://github.com/remyhonig/elfeed-org) find feeds.
> elfeed-org: theme rmh-elfeed-org-files (fix path)

- no-littering.el
repos: https://github.com/davep/uptimes.el
This file is used to store an s-expression.
This is the only configuration/data file of the package.
This package does/doesn't take care of creating the containing
directory if necessary.
> uptimes: theme uptimes-database

- no-littering.el
Themes https://codeberg.org/ideasman42/emacs-spell-fu
This appears to be the only path-related variable used by spell-fu,
and is used to store multiple files. The docstring says that it's "The
directory to store dictionary data."
The files seem to come in pairs, one .el.data containing an s-exp and
a .txt file containing one word per line. Each pair represents one
dictionary, including the user's personal dictionary.
The personal dictionary suggests that maybe this should be under etc,
but most of the contents seem to be cache. The upstream author doesn't
provide a way to separate them, so I decided to just go with the
majority and call it var.
The package does handle creating the directory as necessary.
> spell-fu: theme spell-fu-directory

- no-littering.el
This sets `eshell-rc-script` and `eshell-login-script`.  These script files are
the Eshell startup file, and do not contain data.  Instead, they contain a
series of Eshell commands, similar to `.bashrc`.
The moving of these files from `var` to `etc` follows the same reasoning used in
#138 for moving the Eshell aliases file.
The current configured values of these variables are `var/eshell/profile` and
`var/eshell/login`.  Following the conventions, they are changed to
`etc/eshell/rc` and `etc/eshell/login`, given that the suffix "-script" is
similar to a suffix "-file".
> eshell: Theme `eshell-rc-script` separately from other Eshell files

- no-littering.el
This is the path to a directory containing a single file named `stored-dictionary`, which contains the dictionary for the `lsp-ltex` emacs client for the ltex LanguageTool language-server, see https://github.com/emacs-languagetool/lsp-ltex.
The contained `stored-dictionary` file is stored in s-expression format.
This package asks the user via a prompt if it should create that directory when the use interactively adds a word to the ltex dictionary for the first time.
This is the only configuration/data file of the package, except `lsp-ltex-server-store-path`, but this is already correctly in `var` as it's by default set under the themed `lsp-server-install-dir`.
> lsp-ltex: theme lsp-ltex-user-rules-path

- no-littering.el
Theme gnus-notes-top-dir', it is used to story any data that the
package writes.
The data is either /articles/ an S-expression or /crumbs/ a folder
that contains S-expressions.
The package takes care of creating it's directory.
- Repo-link: https://github.com/deusmax/gnus-notes
> gnus-notes: Theme gnus-notes-top-dir

- no-littering.el
- Theme gnus-startup-file' it was suggested that this variable
shouldn't be themed however gnus own configuration `newsrc.eld` is
based on `(concat gnus-startup-file ".eld")` whichm means themeing
is the only way to theme `newsrc.eld`.
- There are no downsides on this except that gnus won't read other
readers newsrc anymore which is suggested anyway.
Fixes: dcc96cbf5f018a91d406926d3b69715847ef665a
Re: #142
> gnus: Theme gnus-startup-file so newsrc.eld is themed

- no-littering.el
- elfeed-autotag-files :: the files is used to tag elfeed entries
based on their properties similar to  elfeed-org but with defining feeds.
The files contain the only configuration/data file of the package.
- The directory for the files that the package uses is already created
for another package.
Repo-link: https://github.com/paulelms/elfeed-autotag
> elfeed-autoag: Theme elfeed-autotag-files

- README.org
- migrate.org
- no-littering.el
I was surprised to see that the README stated that no-littering could not help the user migrate their files while, actually, there was a handy migration guide in the repository. Moreover, some steps in the guide seemed unclear to me. This PR thus:
* Mentions the `migrate.org` file in the README and in the comments at the top of `no-litter.el`.
* Improves the way the results of the Elisp Babel block containing the migration script generator are printed in the org file.
* Improves the wording and the spelling in that same file.
> Improve migrate.org and mention it in the README

- no-littering.el
ielm-history-file-name is a variable new to Emacs 30. At the time of
writing, this is the only data file defined by IELM.
> ielm: theme ielm-history-file-name
